src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Category $category = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }


}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{# {% block title %}Mon blog, yeah!{% endblock %} #}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{% block nav %} {{parent()}} {% endblock %}

<div class="container justify-content-between d-flex flex-wrap">
   
       {% for article in articles %}
       <div class="col-4 h-full h-auto pe-5">
    <div class="card mb-5 h-full h-auto">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVecIZatL6lcQydGbzjWBr-ExnDrMzxzyyCg&s" class="card-img-top" alt="...">
        <div class="card-body">
            <h2 class="card-title">{{ article.title }}</h2>
            <p class="card-text">{{ article.content}}</p>
            <p>Escrito el {{ article.createdAt | date('d/m/Y') }}</p>
                        <p><em>{{ article.category.name }}</em></p>

        </div>

    </div>
    </div>
  {% endfor %}
</div>
{% endblock %}